/******************************************************************************
 Copyright (c) 2017 Qualcomm Technologies International, Ltd.
 All Rights Reserved.
 Qualcomm Technologies International, Ltd. Confidential and Proprietary.
 ******************************************************************************/
/*! \file qmesh_config_model_internal.h
 *
 *  \brief Qmesh Configuration Model Packet details.
 *
 *   This file contains the offsets and length for Configuration Model packets
 *
 */
 /*****************************************************************************/

#ifndef _QMESH_CONFIG_MODEL_INTERNAL_H_
#define _QMESH_CONFIG_MODEL_INTERNAL_H_

#include "qmesh_types.h"

/*============================================================================*
   Public Definitions
 *============================================================================*/
#define CONFIG_MESSAGE_OPCODE_OFFSET    0UL

#define KEY_INDEXES_3B_PACK_SIZE       3UL

/* Size of opcodes */
#define CONFIG_MESSAGE_ONEB_OPCODE_SIZE     1UL
#define CONFIG_MESSAGE_TWOB_OPCODE_SIZE     2UL
#define CONFIG_MESSAGE_THREEB_OPCODE_SIZE     3UL

/* Size of Configuration Model LastETag in words. */
#define CONFIG_LAST_ETAG_SIZE_IN_WORDS  (4)
#define CONFIG_RESET_SIGNATURE_SIZE     (8)

/* Secure network beacon state */
#define NOT_BROADCASTING_SECURE_NET_BEACON 0x00
#define BROADCASTING_SECURE_NET_BEACON     0x01

/* Proxy state */
#define NOT_RUNNING_MESH_PROXY_SERVICE  0x00
#define RUNNING_MESH_PROXY_SERVICE      0x01

/* Identity state */
#define NOT_ADV_USING_NODE_IDENTITY     0x00
#define ADV_USING_NODE_IDENTITY         0x01

/* Default TTL */
#define DEFAULT_TTL                     0x05

/* Relay state */
#define RELAY_STATE_NOT_RELAYING        0x00
#define RELAY_STATE_RELAYING            0x01

#define KEY_INDEX_SIZE 2UL

#define MAX_COMPOSITION_DATA_LEN 50

/* Publication and Subscription Status Length excluding Model ID */
#define CONFIG_MODEL_PUBLICATION_STATUS_LEN 	12
#define CONFIG_MODEL_SUBSCRIPTION_STATUS_LEN 	7

/* Beacon status Len in Octets */
#define CONFIG_BEACON_STATUS_LEN 1

#define MAX_MODEL_SUBSCRIPTION_LEN 9

#define MAX_MODEL_SUBSCRIPTION_LIST_LEN 50UL

#define NET_KEY_STATUS_LEN 3

#define MAX_KEY_LIST_LEN MAX_NUM_SUB_NET_PER_PROVISIONING

#define KEY_REFRESH_PHASE_RESP_LEN 4

#define MAX_MODEL_APP_LEN 9

#define MAX_MODEL_APP_GET_LEN 37

#define FRND_TIMEOUT_STATUS_LEN 5

#define ONE_BYTE_OPCODE_LEN 1
#define TWO_BYTE_OPCODE_LEN 2

#define COMPOSITION_DATA_SIG_NUM_MODELS_OFFSET          33
#define COMPOSITION_DATA_VENDOR_NUM_MODELS_OFFSET       34

#define NODE_IDENTITY_STATUS_OPCODE_IDX         (0)
#define NODE_IDENTITY_STATUS_OPCODE_LEN         (2)
#define NODE_IDENTITY_STATUS_IDX                (NODE_IDENTITY_STATUS_OPCODE_IDX + NODE_IDENTITY_STATUS_OPCODE_LEN)
#define NODE_IDENTITY_STATUS_LEN                (1)
#define NODE_IDENTITY_STATUS_NID_IDX            (NODE_IDENTITY_STATUS_IDX + NODE_IDENTITY_STATUS_LEN)
#define NODE_IDENTITY_STATUS_NID_LEN            (2)
#define NODE_IDENTITY_STATUS_IDENTITY_VAL_IDX   (NODE_IDENTITY_STATUS_NID_IDX + NODE_IDENTITY_STATUS_NID_LEN)
#define NODE_IDENTITY_STATUS_IDENTITY_VAL_LEN   (1)


#define NODE_IDENTITY_REQ_NID_IDX               (0)
#define NODE_IDENTITY_REQ_NID_LEN               (2)
#define NODE_IDENTITY_REQ_IDENTITY_VAL_IDX      (NODE_IDENTITY_REQ_NID_IDX + NODE_IDENTITY_REQ_NID_LEN)

#define NODE_IDENTITY_STATUS_MSG_LEN            (NODE_IDENTITY_STATUS_OPCODE_LEN + NODE_IDENTITY_STATUS_LEN + \
                                                 NODE_IDENTITY_STATUS_NID_LEN + NODE_IDENTITY_STATUS_IDENTITY_VAL_LEN)

#define HEART_BEAT_SUBSCRIPTION_STATUS_MSG_LEN         11
#define HEART_BEAT_PUBLICATION_STATUS_MSG_LEN          11

#define NETWORK_TRANSMIT_STATUS_OPCODE_LEN          (TWO_BYTE_OPCODE_LEN)
#define NETWORK_TRANSMIT_STATE_LEN                  (1)
#define NETWORK_TRANSMIT_STATUS_MSG_LEN             (NETWORK_TRANSMIT_STATUS_OPCODE_LEN + NETWORK_TRANSMIT_STATE_LEN)

/*! \brief Config model message retransmit interval */
#define CONFIG_MODEL_MSG_RETRANSMIT_INTERVAL        (150 * QMESH_MILLISECOND)

/*! \brief Time between receiving Node reset request and actually resetting the node */
#define CONFIG_MODEL_NODE_RESET_INTERVAL            (50 * QMESH_MILLISECOND)

/*! \brief Config model message retransmit interval */
#define CONFIG_MODEL_RETRANSMIT_COUNT               (10)

/* Composition data */
#define CONF_CLI_COMP_DATA_STATUS_PAGE_NUM_IDX 0
#define CONF_CLI_COMP_DATA_STATUS_PAGE_NUM_LEN 1
#define CONF_CLI_COMP_DATA_STATUS_CID_IDX (CONF_CLI_COMP_DATA_STATUS_PAGE_NUM_IDX + \
                                            CONF_CLI_COMP_DATA_STATUS_PAGE_NUM_LEN)
#define CONF_CLI_COMP_DATA_STATUS_CID_LEN 2
#define CONF_CLI_COMP_DATA_STATUS_PID_IDX (CONF_CLI_COMP_DATA_STATUS_CID_IDX + \
                                            CONF_CLI_COMP_DATA_STATUS_CID_LEN)
#define CONF_CLI_COMP_DATA_STATUS_PID_LEN 2 
#define CONF_CLI_COMP_DATA_STATUS_VID_IDX (CONF_CLI_COMP_DATA_STATUS_PID_IDX + \
                                            CONF_CLI_COMP_DATA_STATUS_PID_LEN)
#define CONF_CLI_COMP_DATA_STATUS_VID_LEN 2
#define CONF_CLI_COMP_DATA_STATUS_CRPL_IDX (CONF_CLI_COMP_DATA_STATUS_VID_IDX + \
                                             CONF_CLI_COMP_DATA_STATUS_VID_LEN)
#define CONF_CLI_COMP_DATA_STATUS_CRPL_LEN 2 
#define CONF_CLI_COMP_DATA_STATUS_FEATURE_MASK_IDX (CONF_CLI_COMP_DATA_STATUS_CRPL_IDX + \
                                                     CONF_CLI_COMP_DATA_STATUS_CRPL_LEN)
#define CONF_CLI_COMP_DATA_STATUS_FEATURE_MASK_LEN 2

/* Config Model publication status */
#define CONF_CLI_MODEL_PUB_STATUS_STATUS_IDX 0
#define CONF_CLI_MODEL_PUB_STATUS_STATUS_LEN 1
#define CONF_CLI_MODEL_PUB_STATUS_ELM_ADDR_IDX (CONF_CLI_MODEL_PUB_STATUS_STATUS_IDX + CONF_CLI_MODEL_PUB_STATUS_STATUS_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_ELM_ADDR_LEN 2
#define CONF_CLI_MODEL_PUB_STATUS_PUB_ADDR_IDX (CONF_CLI_MODEL_PUB_STATUS_ELM_ADDR_IDX + CONF_CLI_MODEL_PUB_STATUS_ELM_ADDR_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_PUB_ADDR_LEN 2 
#define CONF_CLI_MODEL_PUB_STATUS_APP_KEY_IDX (CONF_CLI_MODEL_PUB_STATUS_PUB_ADDR_IDX + CONF_CLI_MODEL_PUB_STATUS_PUB_ADDR_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_APP_KEY_LEN 2
#define CONF_CLI_MODEL_PUB_STATUS_PUB_TTL_IDX (CONF_CLI_MODEL_PUB_STATUS_APP_KEY_IDX + CONF_CLI_MODEL_PUB_STATUS_APP_KEY_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_PUB_TTL_LEN 1
#define CONF_CLI_MODEL_PUB_STATUS_PUB_PERIOD_IDX (CONF_CLI_MODEL_PUB_STATUS_PUB_TTL_IDX + CONF_CLI_MODEL_PUB_STATUS_PUB_TTL_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_PUB_PERIOD_LEN 1 
#define CONF_CLI_MODEL_PUB_STATUS_RTX_IDX (CONF_CLI_MODEL_PUB_STATUS_PUB_PERIOD_IDX + CONF_CLI_MODEL_PUB_STATUS_PUB_PERIOD_LEN)
#define CONF_CLI_MODEL_PUB_STATUS_RTX_LEN 1 
#define CONF_CLI_MODEL_PUB_STATUS_MODEL_ID_IDX (CONF_CLI_MODEL_PUB_STATUS_RTX_IDX + CONF_CLI_MODEL_PUB_STATUS_RTX_LEN)

/* Config Model subscription status */
#define CONF_CLI_SUB_STATUS_STATUS_IDX 0
#define CONF_CLI_SUB_STATUS_STATUS_LEN 1
#define CONF_CLI_SUB_STATUS_ELM_ADDR_IDX (CONF_CLI_SUB_STATUS_STATUS_IDX + CONF_CLI_SUB_STATUS_STATUS_LEN)
#define CONF_CLI_SUB_STATUS_ELM_ADDR_LEN 2
#define CONF_CLI_SUB_STATUS_ADDR_IDX (CONF_CLI_SUB_STATUS_ELM_ADDR_IDX + CONF_CLI_SUB_STATUS_ELM_ADDR_LEN)
#define CONF_CLI_SUB_STATUS_ADDR_LEN 2
#define CONF_CLI_SUB_STATUS_MODEL_ID_IDX (CONF_CLI_SUB_STATUS_ADDR_IDX + CONF_CLI_SUB_STATUS_ADDR_LEN)

/* Config Model Key Refresh Phase Status */
#define CONFIG_KEY_REFRESH_PHASE_STATUS__STATUS__IDX 0
#define CONFIG_KEY_REFRESH_PHASE_STATUS__STATUS__LEN 1
#define CONFIG_KEY_REFRESH_PHASE_STATUS__NET_KEY_ID__IDX (CONFIG_KEY_REFRESH_PHASE_STATUS__STATUS__IDX + \
                                                          CONFIG_KEY_REFRESH_PHASE_STATUS__STATUS__LEN)
#define CONFIG_KEY_REFRESH_PHASE_STATUS__NET_KEY_ID__LEN 2
#define CONFIG_KEY_REFRESH_PHASE_STATUS__PHASE__IDX (CONFIG_KEY_REFRESH_PHASE_STATUS__NET_KEY_ID__IDX + \
                                                     CONFIG_KEY_REFRESH_PHASE_STATUS__NET_KEY_ID__LEN)

/* Config Model Beacon Set/Get */
#define CONFIG_BEACON_GET__OPCODE__IDX 0
#define CONFIG_BEACON_GET__OPCODE__LEN 2
#define CONFIG_BEACON_GET__MSG_LEN (CONFIG_BEACON_GET__OPCODE__LEN)

#define CONFIG_BEACON_SET__OPCODE__IDX 0
#define CONFIG_BEACON_SET__OPCODE__LEN 2
#define CONFIG_BEACON_SET__STATE__IDX (CONFIG_BEACON_SET__OPCODE__IDX + \
                                       CONFIG_BEACON_SET__OPCODE__LEN)
#define CONFIG_BEACON_SET__STATE__LEN 1
#define CONFIG_BEACON_SET__MSG_LEN (CONFIG_BEACON_SET__OPCODE__LEN + \
                                    CONFIG_BEACON_SET__STATE__LEN)

/* Config Model Composition Get */
#define CONFIG_COMPOSITION_GET__OPCODE__IDX 0
#define CONFIG_COMPOSITION_GET__OPCODE__LEN 2
#define CONFIG_COMPOSITION_GET__PAGE__IDX (CONFIG_COMPOSITION_GET__OPCODE__IDX + \
                                           CONFIG_COMPOSITION_GET__OPCODE__LEN)
#define CONFIG_COMPOSITION_GET__PAGE__LEN 1
#define CONFIG_COMPOSITION_GET__MSG_LEN (CONFIG_COMPOSITION_GET__OPCODE__LEN + \
                                         CONFIG_COMPOSITION_GET__PAGE__LEN)

/* Config Model Default TTL Get/Set */
#define CONFIG_DEFAULT_TTL_GET__OPCODE__IDX 0
#define CONFIG_DEFAULT_TTL_GET__OPCODE__LEN 2
#define CONFIG_DEFAULT_TTL_GET__MSG_LEN (CONFIG_DEFAULT_TTL_GET__OPCODE__LEN)

#define CONFIG_DEFAULT_TTL_SET__OPCODE__IDX 0
#define CONFIG_DEFAULT_TTL_SET_OPCODE__LEN 2
#define CONFIG_DEFAULT_TTL_SET__TTL__IDX (CONFIG_DEFAULT_TTL_SET__OPCODE__IDX + \
                                          CONFIG_DEFAULT_TTL_SET_OPCODE__LEN)
#define CONFIG_DEFAULT_TTL_SET__TTL__LEN 1
#define CONFIG_DEFAULT_TTL_SET__MSG_LEN (CONFIG_DEFAULT_TTL_SET_OPCODE__LEN + \
                                         CONFIG_DEFAULT_TTL_SET__TTL__LEN)

/* Config Model Relay Get/Set */
#define CONFIG_MODEL_RELAY_GET__OPCODE__IDX 0
#define CONFIG_MODEL_RELAY_GET__OPCODE__LEN 2
#define CONFIG_MODEL_RELAY_GET__MSG_LEN (CONFIG_MODEL_RELAY_GET__OPCODE__LEN)

#define CONFIG_MODEL_RELAY_SET__OPCODE__IDX 0
#define CONFIG_MODEL_RELAY_SET__OPCODE__LEN 2
#define CONFIG_MODEL_RELAY_SET__RELAY__IDX (CONFIG_MODEL_RELAY_SET__OPCODE__IDX +\
                                           CONFIG_MODEL_RELAY_SET__OPCODE__LEN)
#define CONFIG_MODEL_RELAY_SET__RELAY__LEN 1
#define CONFIG_MODEL_RELAY_SET__RELAY_RETRANSMIT__IDX (CONFIG_MODEL_RELAY_SET__RELAY__IDX + \
                                                       CONFIG_MODEL_RELAY_SET__RELAY__LEN)
#define CONFIG_MODEL_RELAY_SET__RELAY_RETRANSMIT__LEN 1
#define CONFIG_MODEL_RELAY_SET__MSG_LEN (CONFIG_MODEL_RELAY_SET__OPCODE__LEN + \
                                         CONFIG_MODEL_RELAY_SET__RELAY__LEN + \
                                         CONFIG_MODEL_RELAY_SET__RELAY_RETRANSMIT__LEN)

/* Config Model Network Key Add */
#define CONFIG_MODEL_NETWORK_KEY_ADD__OPCODE_IDX 0
#define CONFIG_MODEL_NETWORK_KEY_ADD__OPCODE_LEN 2
#define CONFIG_MODEL_NETWORK_KEY_ADD__KEY_IDX__IDX (CONFIG_MODEL_NETWORK_KEY_ADD__OPCODE_IDX + \
                                                    CONFIG_MODEL_NETWORK_KEY_ADD__OPCODE_LEN)
#define CONFIG_MODEL_NETWORK_KEY_ADD__KEY_IDX__LEN 2
#define CONFIG_MODEL_NETWORK_KEY_ADD__NW_KEY__IDX (CONFIG_MODEL_NETWORK_KEY_ADD__KEY_IDX__IDX + \
                                                   CONFIG_MODEL_NETWORK_KEY_ADD__KEY_IDX__LEN)
#define CONFIG_MODEL_NETWORK_KEY_ADD__NW_KEY__LEN 16
#define CONFIG_MODEL_NETWORK_KEY_ADD__MSG_LEN (CONFIG_MODEL_NETWORK_KEY_ADD__OPCODE_LEN + \
                                               CONFIG_MODEL_NETWORK_KEY_ADD__KEY_IDX__LEN + \
                                               CONFIG_MODEL_NETWORK_KEY_ADD__NW_KEY__LEN)

/* Config Model Network Key Update */
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__OPCODE_IDX 0
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__OPCODE_LEN 2
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__KEY_IDX__IDX (CONFIG_MODEL_NETWORK_KEY_UPDATE__OPCODE_IDX + \
                                                       CONFIG_MODEL_NETWORK_KEY_UPDATE__OPCODE_LEN)
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__KEY_IDX__LEN 2
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__NW_KEY__IDX (CONFIG_MODEL_NETWORK_KEY_UPDATE__KEY_IDX__IDX + \
                                                      CONFIG_MODEL_NETWORK_KEY_UPDATE__KEY_IDX__LEN)
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__NW_KEY__LEN 16
#define CONFIG_MODEL_NETWORK_KEY_UPDATE__MSG_LEN (CONFIG_MODEL_NETWORK_KEY_UPDATE__OPCODE_LEN + \
                                                  CONFIG_MODEL_NETWORK_KEY_UPDATE__KEY_IDX__LEN + \
                                                  CONFIG_MODEL_NETWORK_KEY_UPDATE__NW_KEY__LEN)

/* Config Model Network Key Delete */
#define CONFIG_MODEL_NETWORK_KEY_DELETE__OPCODE_IDX 0
#define CONFIG_MODEL_NETWORK_KEY_DELETE__OPCODE_LEN 2
#define CONFIG_MODEL_NETWORK_KEY_DELETE__KEY_IDX__IDX (CONFIG_MODEL_NETWORK_KEY_DELETE__OPCODE_IDX + \
                                                       CONFIG_MODEL_NETWORK_KEY_DELETE__OPCODE_LEN)
#define CONFIG_MODEL_NETWORK_KEY_DELETE__KEY_IDX__LEN 2
#define CONFIG_MODEL_NETWORK_KEY_DELETE__MSG_LEN (CONFIG_MODEL_NETWORK_KEY_DELETE__OPCODE_LEN + \
                                                  CONFIG_MODEL_NETWORK_KEY_DELETE__KEY_IDX__LEN)

/* Config Model Network Key Get */
#define CONFIG_MODEL_NETWORK_KEY_GET__OPCODE_IDX 0
#define CONFIG_MODEL_NETWORK_KEY_GET__OPCODE_LEN 2
#define CONFIG_MODEL_NETWORK_KEY_GET__MSG_LEN (CONFIG_MODEL_NETWORK_KEY_GET__OPCODE_LEN)

/* Config Model App Key Add */
#define CONFIG_MODEL_APP_KEY_ADD__OPCODE_IDX 0
#define CONFIG_MODEL_APP_KEY_ADD__OPCODE_LEN 1
#define CONFIG_MODEL_APP_KEY_ADD__KEY_IDX__IDX (CONFIG_MODEL_APP_KEY_ADD__OPCODE_IDX + \
                                                CONFIG_MODEL_APP_KEY_ADD__OPCODE_LEN)
#define CONFIG_MODEL_APP_KEY_ADD__KEY_IDX__LEN 3
#define CONFIG_MODEL_APP_KEY_ADD__APP_KEY__IDX (CONFIG_MODEL_APP_KEY_ADD__KEY_IDX__IDX + \
                                                CONFIG_MODEL_APP_KEY_ADD__KEY_IDX__LEN)
#define CONFIG_MODEL_APP_KEY_ADD__APP_KEY__LEN 16
#define CONFIG_MODEL_APP_KEY_ADD__MSG_LEN (CONFIG_MODEL_APP_KEY_ADD__OPCODE_LEN + \
                                           CONFIG_MODEL_APP_KEY_ADD__KEY_IDX__LEN + \
                                           CONFIG_MODEL_APP_KEY_ADD__APP_KEY__LEN)

/* Config Model App Key Update */
#define CONFIG_MODEL_APP_KEY_UPDATE__OPCODE_IDX 0
#define CONFIG_MODEL_APP_KEY_UPDATE__OPCODE_LEN 1
#define CONFIG_MODEL_APP_KEY_UPDATE__KEY_IDX__IDX (CONFIG_MODEL_APP_KEY_UPDATE__OPCODE_IDX + \
                                                   CONFIG_MODEL_APP_KEY_UPDATE__OPCODE_LEN)
#define CONFIG_MODEL_APP_KEY_UPDATE__KEY_IDX__LEN 3
#define CONFIG_MODEL_APP_KEY_UPDATE__APP_KEY__IDX (CONFIG_MODEL_APP_KEY_UPDATE__KEY_IDX__IDX + \
                                                   CONFIG_MODEL_APP_KEY_UPDATE__KEY_IDX__LEN)
#define CONFIG_MODEL_APP_KEY_UPDATE__APP_KEY__LEN 16
#define CONFIG_MODEL_APP_KEY_UPDATE__MSG_LEN (CONFIG_MODEL_APP_KEY_UPDATE__OPCODE_LEN + \
                                              CONFIG_MODEL_APP_KEY_UPDATE__KEY_IDX__LEN + \
                                              CONFIG_MODEL_APP_KEY_UPDATE__APP_KEY__LEN)

/* Config Model App Key Delete */
#define CONFIG_MODEL_APP_KEY_DELETE__OPCODE_IDX 0
#define CONFIG_MODEL_APP_KEY_DELETE__OPCODE_LEN 2
#define CONFIG_MODEL_APP_KEY_DELETE__KEY_IDX__IDX (CONFIG_MODEL_APP_KEY_DELETE__OPCODE_IDX + \
                                                   CONFIG_MODEL_APP_KEY_DELETE__OPCODE_LEN)
#define CONFIG_MODEL_APP_KEY_DELETE__KEY_IDX__LEN 3
#define CONFIG_MODEL_APP_KEY_DELETE__MSG_LEN (CONFIG_MODEL_APP_KEY_DELETE__OPCODE_LEN + \
                                              CONFIG_MODEL_APP_KEY_DELETE__KEY_IDX__LEN)

/* Config Model App Key Get */
#define CONFIG_MODEL_APP_KEY_GET__OPCODE_IDX 0
#define CONFIG_MODEL_APP_KEY_GET__OPCODE_LEN 2
#define CONFIG_MODEL_APP_KEY_GET__KEY_IDX__IDX (CONFIG_MODEL_APP_KEY_GET__OPCODE_IDX + \
                                                CONFIG_MODEL_APP_KEY_GET__OPCODE_LEN)
#define CONFIG_MODEL_APP_KEY_GET__KEY_IDX__LEN 2
#define CONFIG_MODEL_APP_KEY_GET__MSG_LEN (CONFIG_MODEL_APP_KEY_GET__OPCODE_LEN + \
                                           CONFIG_MODEL_APP_KEY_GET__KEY_IDX__LEN)

/* Config Model Key Refresh Phase Get */
#define CONFIG_MODEL_KEY_REFRESH_PHASE_GET__OPCODE__IDX 0
#define CONFIG_MODEL_KEY_REFRESH_PHASE_GET__OPCODE__LEN 2
#define CONFIG_MODEL_KEY_REFRESH_PHASE_GET__NET_KEY__IDX (CONFIG_MODEL_KEY_REFRESH_PHASE_GET__OPCODE__IDX + \
                                                          CONFIG_MODEL_KEY_REFRESH_PHASE_GET__OPCODE__LEN)
#define CONFIG_MODEL_KEY_REFRESH_PHASE_GET__NET_KEY__LEN 2
#define CONFIG_MODEL_KEY_REFRESH_PHASE_GET__MSG_LEN (CONFIG_MODEL_KEY_REFRESH_PHASE_GET__OPCODE__LEN + \
                                                     CONFIG_MODEL_KEY_REFRESH_PHASE_GET__NET_KEY__LEN)

/* Config Model Key Refresh Phase Set */
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__OPCODE__IDX 0
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__OPCODE__LEN 2
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__NET_KEY__IDX (CONFIG_MODEL_KEY_REFRESH_PHASE_SET__OPCODE__IDX + \
                                                          CONFIG_MODEL_KEY_REFRESH_PHASE_SET__OPCODE__LEN)
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__NET_KEY__LEN 2
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__PHASE__IDX (CONFIG_MODEL_KEY_REFRESH_PHASE_SET__NET_KEY__IDX + \
                                                        CONFIG_MODEL_KEY_REFRESH_PHASE_SET__NET_KEY__LEN)
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__PHASE__LEN 1
#define CONFIG_MODEL_KEY_REFRESH_PHASE_SET__MSG_LEN (CONFIG_MODEL_KEY_REFRESH_PHASE_SET__OPCODE__LEN + \
                                                     CONFIG_MODEL_KEY_REFRESH_PHASE_SET__NET_KEY__LEN + \
                                                     CONFIG_MODEL_KEY_REFRESH_PHASE_SET__PHASE__LEN)

/* Config Model Gatt Proxy Get State */
#define CONFIG_MODEL_GATT_PROXY_GET__OPCODE__IDX 0
#define CONFIG_MODEL_GATT_PROXY_GET__OPCODE__LEN 2
#define CONFIG_MODEL_GATT_PROXY_GET__MSG_LEN (CONFIG_MODEL_GATT_PROXY_GET__OPCODE__LEN)

/* Config Model Gatt Proxy Set State */
#define CONFIG_MODEL_GATT_PROXY_SET__OPCODE__IDX 0
#define CONFIG_MODEL_GATT_PROXY_SET__OPCODE__LEN 2
#define CONFIG_MODEL_GATT_PROXY_SET__STATE__IDX (CONFIG_MODEL_GATT_PROXY_SET__OPCODE__IDX + \
                                                 CONFIG_MODEL_GATT_PROXY_SET__OPCODE__LEN)
#define CONFIG_MODEL_GATT_PROXY_SET__STATE__LEN 1
#define CONFIG_MODEL_GATT_PROXY_SET__MSG_LEN (CONFIG_MODEL_GATT_PROXY_SET__OPCODE__LEN + \
                                              CONFIG_MODEL_GATT_PROXY_SET__STATE__LEN)

/* Config Model Node Identity Get */
#define CONFIG_MODEL_NODE_IDENTITY_GET__OPCODE__IDX 0
#define CONFIG_MODEL_NODE_IDENTITY_GET__OPCODE__LEN 2
#define CONFIG_MODEL_NODE_IDENTITY_GET__NET_KEY_IDX__IDX (CONFIG_MODEL_NODE_IDENTITY_GET__OPCODE__IDX + \
                                                          CONFIG_MODEL_NODE_IDENTITY_GET__OPCODE__LEN)
#define CONFIG_MODEL_NODE_IDENTITY_GET__NET_KEY_IDX__LEN 2
#define CONFIG_MODEL_NODE_IDENTITY_GET__MSG_LEN (CONFIG_MODEL_NODE_IDENTITY_GET__OPCODE__LEN + \
                                                 CONFIG_MODEL_NODE_IDENTITY_GET__NET_KEY_IDX__LEN)

/* Config Model Node Identity Set */
#define CONFIG_MODEL_NODE_IDENTITY_SET__OPCODE__IDX 0
#define CONFIG_MODEL_NODE_IDENTITY_SET__OPCODE__LEN 2
#define CONFIG_MODEL_NODE_IDENTITY_SET__NET_KEY_IDX__IDX (CONFIG_MODEL_NODE_IDENTITY_SET__OPCODE__IDX + \
                                                          CONFIG_MODEL_NODE_IDENTITY_SET__OPCODE__LEN)
#define CONFIG_MODEL_NODE_IDENTITY_SET__NET_KEY_IDX__LEN 2
#define CONFIG_MODEL_NODE_IDENTITY_SET__IDENTITY_STATE__IDX (CONFIG_MODEL_NODE_IDENTITY_SET__NET_KEY_IDX__IDX + \
                                                             CONFIG_MODEL_NODE_IDENTITY_SET__NET_KEY_IDX__LEN)
#define CONFIG_MODEL_NODE_IDENTITY_SET__IDENTITY_STATE__LEN 1
#define CONFIG_MODEL_NODE_IDENTITY_SET__MSG_LEN (CONFIG_MODEL_NODE_IDENTITY_SET__OPCODE__LEN + \
                                                 CONFIG_MODEL_NODE_IDENTITY_SET__NET_KEY_IDX__LEN + \
                                                 CONFIG_MODEL_NODE_IDENTITY_SET__IDENTITY_STATE__LEN)

/* Config Model Publication Get */
#define CONFIG_MODEL_PUBLICATION_GET__OPCODE__IDX 0
#define CONFIG_MODEL_PUBLICATION_GET__OPCODE__LEN 2
#define CONFIG_MODEL_PUBLICATION_GET__ELE_ADDR__IDX (CONFIG_MODEL_PUBLICATION_GET__OPCODE__IDX + \
                                                     CONFIG_MODEL_PUBLICATION_GET__OPCODE__LEN)
#define CONFIG_MODEL_PUBLICATION_GET__ELE_ADDR__LEN 2
#define CONFIG_MODEL_PUBLICATION_GET__MODEL_ID__IDX (CONFIG_MODEL_PUBLICATION_GET__ELE_ADDR__IDX + \
                                                     CONFIG_MODEL_PUBLICATION_GET__ELE_ADDR__LEN)
/* CONFIG_MODEL_PUBLICATION_GET length excluding the model length */
#define CONFIG_MODEL_PUBLICATION_GET__MSG_LEN (CONFIG_MODEL_PUBLICATION_GET__OPCODE__LEN + \
                                               CONFIG_MODEL_PUBLICATION_GET__ELE_ADDR__LEN)

/* Config model publication set */
#define CONFIG_MODEL_PUBLICATION_SET__OPCODE__IDX 0
#define CONFIG_MODEL_PUBLICATION_SET__OPCODE__LEN 1
#define CONFIG_MODEL_PUBLICATION_SET__ELM_ADDR__IDX (CONFIG_MODEL_PUBLICATION_SET__OPCODE__IDX +\
                                                     CONFIG_MODEL_PUBLICATION_SET__OPCODE__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__ELM_ADDR__LEN 2
#define CONFIG_MODEL_PUBLICATION_SET__PUB_ADDR__IDX (CONFIG_MODEL_PUBLICATION_SET__ELM_ADDR__IDX + \
                                                     CONFIG_MODEL_PUBLICATION_SET__ELM_ADDR__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__PUB_ADDR__LEN 2 
#define CONFIG_MODEL_PUBLICATION_SET__PUB_APP_KEY__IDX (CONFIG_MODEL_PUBLICATION_SET__PUB_ADDR__IDX + \
                                                        CONFIG_MODEL_PUBLICATION_SET__PUB_ADDR__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__PUB_APP_KEY__LEN 2
#define CONFIG_MODEL_PUBLICATION_SET__PUB_TTL__IDX (CONFIG_MODEL_PUBLICATION_SET__PUB_APP_KEY__IDX + \
                                                    CONFIG_MODEL_PUBLICATION_SET__PUB_APP_KEY__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__PUB_TTL__LEN 1
#define CONFIG_MODEL_PUBLICATION_SET__PUB_PERIOD__IDX (CONFIG_MODEL_PUBLICATION_SET__PUB_TTL__IDX + \
                                                       CONFIG_MODEL_PUBLICATION_SET__PUB_TTL__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__PUB_PERIOD__LEN 1
#define CONFIG_MODEL_PUBLICATION_SET__RTX_COUNT__IDX (CONFIG_MODEL_PUBLICATION_SET__PUB_PERIOD__IDX + \
                                                      CONFIG_MODEL_PUBLICATION_SET__PUB_PERIOD__LEN)
#define CONFIG_MODEL_PUBLICATION_SET__RTX_COUNT__LEN  1
#define CONFIG_MODEL_PUBLICATION_SET__MODEL_ID__IDX (CONFIG_MODEL_PUBLICATION_SET__RTX_COUNT__IDX + \
                                                     CONFIG_MODEL_PUBLICATION_SET__RTX_COUNT__LEN)
/* CONFIG_MODEL_PUBLICATION_ADDRESS_SET length excluding the model length */
#define CONFIG_MODEL_PUBLICATION_SET__MSG_LEN (CONFIG_MODEL_PUBLICATION_SET__OPCODE__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__ELM_ADDR__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__PUB_ADDR__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__PUB_APP_KEY__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__PUB_TTL__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__PUB_PERIOD__LEN + \
                                              CONFIG_MODEL_PUBLICATION_SET__RTX_COUNT__LEN)

/* Config model publication virtual address set */
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__OPCODE__IDX 0
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__OPCODE__LEN 2
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__ELM_ADDR__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__OPCODE__IDX + \
                                                              CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__OPCODE__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__ELM_ADDR__LEN 2
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_ADDR__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__ELM_ADDR__IDX + \
                                                              CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__ELM_ADDR__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_ADDR__LEN 16
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_APP_KEY__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_ADDR__IDX + \
                                                                 CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_ADDR__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_APP_KEY__LEN 2
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_TTL__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_APP_KEY__IDX + \
                                                             CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_APP_KEY__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_TTL__LEN 1
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_PERIOD__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_TTL__IDX + \
                                                                CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_TTL__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_PERIOD__LEN 1
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__RTX_COUNT__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_PERIOD__IDX + \
                                                               CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_PERIOD__LEN)
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__RTX_COUNT__LEN  1
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__MODEL_ID__IDX (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__RTX_COUNT__IDX + \
                                                              CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__RTX_COUNT__LEN)
/* CONFIG_MODEL_PUBLICATION_VIRTUAL_ADDRESS_SET length excluding the model length */
#define CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__MSG_LEN (CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__OPCODE__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__ELM_ADDR__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_ADDR__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_APP_KEY__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_TTL__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__PUB_PERIOD__LEN + \
                                                        CONFIG_MODEL_PUBLICATION_SET_VIR_ADDR__RTX_COUNT__LEN)

/* Config model subscription */
#define CONFIG_MODEL_SUBSCRIPTION_SET__OPCODE__IDX 0
#define CONFIG_MODEL_SUBSCRIPTION_SET__OPCODE__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_SET__ELM_ADDR__IDX (CONFIG_MODEL_SUBSCRIPTION_SET__OPCODE__IDX + \
                                                      CONFIG_MODEL_SUBSCRIPTION_SET__OPCODE__LEN)
#define CONFIG_MODEL_SUBSCRIPTION_SET__ELM_ADDR__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_SET__ADDR__IDX (CONFIG_MODEL_SUBSCRIPTION_SET__ELM_ADDR__IDX + \
                                                  CONFIG_MODEL_SUBSCRIPTION_SET__ELM_ADDR__LEN)
#define CONFIG_MODEL_SUBSCRIPTION_SET__ADDR__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_SET__MODEL_ID__IDX (CONFIG_MODEL_SUBSCRIPTION_SET__ADDR__IDX + \
                                                      CONFIG_MODEL_SUBSCRIPTION_SET__ADDR__LEN)
/* CONFIG_MODEL_SUBSCRIPTION_ADDRESS_X length excluding the model length */
#define CONFIG_MODEL_SUBSCRIPTION_SET__MSG_LEN (CONFIG_MODEL_SUBSCRIPTION_SET__OPCODE__LEN + \
                                                CONFIG_MODEL_SUBSCRIPTION_SET__ELM_ADDR__LEN + \
                                                CONFIG_MODEL_SUBSCRIPTION_SET__ADDR__LEN)

/* Config model virtual address subscription */
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__OPCODE__IDX 0
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__OPCODE__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__ELM_ADDR__IDX (CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__OPCODE__IDX + \
                                                               CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__OPCODE__LEN)
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__ELM_ADDR__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__UUID__IDX (CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__ELM_ADDR__IDX + \
                                                           CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__ELM_ADDR__LEN)
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__UUID__LEN 16
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__MODEL__ID_IDX (CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__UUID__IDX + \
                                                               CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__UUID__LEN)
/* CONFIG_MODEL_SUBSCRIPTION_VIRTUAL_ADDRESS_X length excluding the model length */
#define CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__MSG_LEN (CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__OPCODE__LEN + \
                                                         CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__ELM_ADDR__LEN + \
                                                         CONFIG_MODEL_SUBSCRIPTION_SET_VIR_ADDR__UUID__LEN)

/* Config model address subscription delete all */
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__OPCODE_IDX 0
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__OPCODE_LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__ELE_ADDR_IDX (CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__OPCODE_IDX + \
                                                         CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__OPCODE_LEN)
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__ELE_ADDR_LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__MODEL_ID__IDX (CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__ELE_ADDR_IDX + \
                                                          CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__ELE_ADDR_LEN)
/* Message length excluding the model id */
#define CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__MSG_LEN (CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__OPCODE_LEN + \
                                                    CONFIG_MODEL_SUBSCRIPTION_DEL_ALL__ELE_ADDR_LEN)

/* Config model SIG subscription get */
#define CONFIG_MODEL_SUBSCRIPTION_GET__OPCODE__IDX 0
#define CONFIG_MODEL_SUBSCRIPTION_GET__OPCODE__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_GET__ELE_ADDR__IDX (CONFIG_MODEL_SUBSCRIPTION_GET__OPCODE__IDX + \
                                                      CONFIG_MODEL_SUBSCRIPTION_GET__OPCODE__LEN)
#define CONFIG_MODEL_SUBSCRIPTION_GET__ELE_ADDR__LEN 2
#define CONFIG_MODEL_SUBSCRIPTION_GET__MODEL_ID__IDX (CONFIG_MODEL_SUBSCRIPTION_GET__ELE_ADDR__IDX + \
                                                      CONFIG_MODEL_SUBSCRIPTION_GET__ELE_ADDR__LEN)
/* Message length excluding the model id */
#define CONFIG_MODEL_SUBSCRIPTION_GET__MSG_LEN (CONFIG_MODEL_SUBSCRIPTION_GET__OPCODE__LEN + \
                                                CONFIG_MODEL_SUBSCRIPTION_GET__ELE_ADDR__LEN)

/* Config Model App Bind/Unbind */
#define CONFIG_MODEL_APP_BIND__OPCODE__IDX 0
#define CONFIG_MODEL_APP_BIND__OPCODE__LEN 2
#define CONFIG_MODEL_APP_BIND__ELE_ADDR__IDX (CONFIG_MODEL_APP_BIND__OPCODE__IDX + \
                                              CONFIG_MODEL_APP_BIND__OPCODE__LEN)
#define CONFIG_MODEL_APP_BIND__ELE_ADDR__LEN 2
#define CONFIG_MODEL_APP_BIND__KEY_ID__IDX (CONFIG_MODEL_APP_BIND__ELE_ADDR__IDX + \
                                            CONFIG_MODEL_APP_BIND__ELE_ADDR__LEN)
#define CONFIG_MODEL_APP_BIND__KEY_ID__LEN 2
#define CONFIG_MODEL_APP_BIND__MODEL_ID_IDX (CONFIG_MODEL_APP_BIND__KEY_ID__IDX + \
                                             CONFIG_MODEL_APP_BIND__KEY_ID__LEN)
/* Message length excluding the model id */
#define CONFIG_MODEL_APP_BIND__MSG_LEN (CONFIG_MODEL_APP_BIND__OPCODE__LEN + \
                                        CONFIG_MODEL_APP_BIND__ELE_ADDR__LEN + \
                                        CONFIG_MODEL_APP_BIND__KEY_ID__LEN)

/* Config Model App Get */
#define CONFIG_MODEL_APP_GET__OPCODE__IDX 0
#define CONFIG_MODEL_APP_GET__OPCODE__LEN 2
#define CONFIG_MODEL_APP_GET__ELE_ADDR__IDX (CONFIG_MODEL_APP_GET__OPCODE__IDX + \
                                             CONFIG_MODEL_APP_GET__OPCODE__LEN)
#define CONFIG_MODEL_APP_GET__ELE_ADDR__LEN 2
#define CONFIG_MODEL_APP_GET__MODEL_ID__IDX (CONFIG_MODEL_APP_GET__ELE_ADDR__IDX + \
                                             CONFIG_MODEL_APP_GET__ELE_ADDR__LEN)
/* Message length excluding the model id */
#define CONFIG_MODEL_APP_GET__MSG_LEN (CONFIG_MODEL_APP_GET__OPCODE__LEN + \
                                       CONFIG_MODEL_APP_GET__ELE_ADDR__LEN)

/* Config Model Node Reset */
#define CONFIG_MODEL_NODE_RESET__OPCODE__IDX 0
#define CONFIG_MODEL_NODE_RESET__OPCODE__LEN 2
#define CONFIG_MODEL_NODE_RESET__MSG_LEN (CONFIG_MODEL_NODE_RESET__OPCODE__LEN)

/* Config Model Friend Get */
#define CONFIG_MODEL_FRIEND_GET__OPCODE__IDX 0
#define CONFIG_MODEL_FRIEND_GET__OPCODE__LEN 2
#define CONFIG_MODEL_FRIEND_GET__MSG_LEN (CONFIG_MODEL_FRIEND_GET__OPCODE__LEN)

/* Config Model Friend Set */
#define CONFIG_MODEL_FRIEND_SET__OPCODE__IDX 0
#define CONFIG_MODEL_FRIEND_SET__OPCODE__LEN 2
#define CONFIG_MODEL_FRIEND_SET__STATE__IDX (CONFIG_MODEL_FRIEND_SET__OPCODE__IDX + \
                                             CONFIG_MODEL_FRIEND_SET__OPCODE__LEN)
#define CONFIG_MODEL_FRIEND_SET__STATE__LEN 1
#define CONFIG_MODEL_FRIEND_SET__MSG_LEN (CONFIG_MODEL_FRIEND_SET__OPCODE__LEN + \
                                          CONFIG_MODEL_FRIEND_SET__STATE__LEN)

/* Config Model Heart Beat Publication/Subscription Get */
#define CONFIG_MODEL_HEARTBEAT_GET__OPCODE__IDX 0
#define CONFIG_MODEL_HEARTBEAT_GET__OPCODE__LEN 2
#define CONFIG_MODEL_HEARTBEAT_GET__MSG_LEN (CONFIG_MODEL_HEARTBEAT_GET__OPCODE__LEN)

/* Config Model Heart Beat Publication Set */
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__OPCODE__IDX 0
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__OPCODE__LEN 2
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__DST_ADDR__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__OPCODE__IDX + \
                                                       CONFIG_MODEL_HEARTBEAT_PUB_SET__OPCODE__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__DST_ADDR__LEN 2
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__COUNT_LOG__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__DST_ADDR__IDX + \
                                                        CONFIG_MODEL_HEARTBEAT_PUB_SET__DST_ADDR__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__COUNT_LOG__LEN 1
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__PERIOD_LOG__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__COUNT_LOG__IDX +\
                                                         CONFIG_MODEL_HEARTBEAT_PUB_SET__COUNT_LOG__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__PERIOD_LOG__LEN 1
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__TTL__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__PERIOD_LOG__IDX + \
                                                  CONFIG_MODEL_HEARTBEAT_PUB_SET__PERIOD_LOG__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__TTL__LEN 1
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__FEATURES__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__TTL__IDX + \
                                                       CONFIG_MODEL_HEARTBEAT_PUB_SET__TTL__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__FEATURES__LEN 2
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__NET_KEY__IDX (CONFIG_MODEL_HEARTBEAT_PUB_SET__FEATURES__IDX + \
                                                      CONFIG_MODEL_HEARTBEAT_PUB_SET__FEATURES__LEN)
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__NET_KEY__LEN 2
#define CONFIG_MODEL_HEARTBEAT_PUB_SET__MSG_LEN (CONFIG_MODEL_HEARTBEAT_PUB_SET__OPCODE__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__DST_ADDR__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__COUNT_LOG__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__PERIOD_LOG__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__TTL__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__FEATURES__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_PUB_SET__NET_KEY__LEN)
/* Config Model Heart Beat Subscription Set */
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__OPCODE__IDX 0
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__OPCODE__LEN 2
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__SRC_ADDR__IDX (CONFIG_MODEL_HEARTBEAT_SUB_SET__OPCODE__IDX + \
                                                       CONFIG_MODEL_HEARTBEAT_SUB_SET__OPCODE__LEN)
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__SRC_ADDR__LEN 2
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__DST_ADDR__IDX (CONFIG_MODEL_HEARTBEAT_SUB_SET__SRC_ADDR__IDX + \
                                                       CONFIG_MODEL_HEARTBEAT_SUB_SET__SRC_ADDR__LEN)
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__DST_ADDR__LEN 2
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__PERIOD_LOG__IDX (CONFIG_MODEL_HEARTBEAT_SUB_SET__DST_ADDR__IDX +\
                                                         CONFIG_MODEL_HEARTBEAT_SUB_SET__DST_ADDR__LEN)
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__PERIOD_LOG__LEN 1
#define CONFIG_MODEL_HEARTBEAT_SUB_SET__MSG_LEN (CONFIG_MODEL_HEARTBEAT_SUB_SET__OPCODE__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_SUB_SET__SRC_ADDR__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_SUB_SET__DST_ADDR__LEN + \
                                                 CONFIG_MODEL_HEARTBEAT_SUB_SET__PERIOD_LOG__LEN)

/* Config Model LPN Poll Timeout Get */
#define CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__OPCODE__IDX 0
#define CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__OPCODE__LEN 2
#define CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__LPN_ADDR__IDX (CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__OPCODE__IDX + \
                                                          CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__OPCODE__LEN)
#define CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__LPN_ADDR__LEN 2
#define CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__MSG_LEN (CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__OPCODE__LEN + \
                                                    CONFIG_MODEL_LPN_POLL_TIMEOUT_GET__LPN_ADDR__LEN)

/* Config Model Network Transmit Get */
#define CONFIG_MODEL_NETWORK_TRANSMIT_GET__OPCODE__IDX 0
#define CONFIG_MODEL_NETWORK_TRANSMIT_GET__OPCODE__LEN 2
#define CONFIG_MODEL_NETWORK_TRANSMIT_GET__MSG_LEN (CONFIG_MODEL_NETWORK_TRANSMIT_GET__OPCODE__LEN)

/* Config Model Network Transmit Set */
#define CONFIG_MODEL_NETWORK_TRANSMIT_SET__OPCODE__IDX 0
#define CONFIG_MODEL_NETWORK_TRANSMIT_SET__OPCODE__LEN 2
#define CONFIG_MODEL_NETWORK_TRANSMIT_SET__NW_TX_COUNT__IDX (CONFIG_MODEL_NETWORK_TRANSMIT_SET__OPCODE__IDX + \
                                                             CONFIG_MODEL_NETWORK_TRANSMIT_SET__OPCODE__LEN)
#define CONFIG_MODEL_NETWORK_TRANSMIT_SET__NW_TX_COUNT__LEN 1
#define CONFIG_MODEL_NETWORK_TRANSMIT_SET__MSG_LEN (CONFIG_MODEL_NETWORK_TRANSMIT_SET__OPCODE__LEN + \
                                                    CONFIG_MODEL_NETWORK_TRANSMIT_SET__NW_TX_COUNT__LEN)

/*============================================================================*
    Enumeration Definitions
 *============================================================================*/


 /*============================================================================*
    Data Type Definitions
 *============================================================================*/
/*! \brief Config Model server context */
typedef struct
{
    QMESH_TIMER_HANDLE_T              reset_tid;         /*!< \brief Reset timer handler */
    QMESH_TIMER_HANDLE_T              retry_tid;         /*!< \brief Retry timer handler */
    uint8_t                           retry_count;       /*!< \brief Num of retry attempts, in case of failure */
    QMESH_ACCESS_PAYLOAD_INFO_T       payload_info;      /*!< \brief Access layer data info */
    QMESH_ACCESS_PAYLOAD_KEY_INFO_T   key_info;          /*!< \brief Key info */
} CONFIG_MODEL_SERVER_CONTEXT_T;

/*============================================================================*
    Public API
 *============================================================================*/


/*!@} */
#endif /* _QMESH_CONFIG_MODEL_INTERNAL_H_ */
